### ISSUE TITLE
Error during install 

### ISSUE THREAD

**Issue by mark1bean** [duncanlutz/create-adobe-extension#1]
Hi Duncan, I got this output from the `npx create-adobe-extension` command.

```
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/mark/.npm/_npx/4cafa1cfa6e3c524/node_modules/create-adobe-extension/create-adobe-extension.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by duncanlutz** [comment]
Hello, thanks for reporting this.

Can you tell me what version of node you're running?

**Comment by mark1bean** [comment]
Ah! Yes my Node was an old version (v12.16.1). I've updated and that issue is solved. Thanks!

As a side note: at first I assumed that "Navigate to the Adobe CEP Extensions folder on your machine" meant the folder where I keep my CEP extension project folders. It might be helpful to clarify what  means. eg. on MacOS `~/Library/Application\ Support/Adobe/CEP/extensions` is the folder. It was good that your tool told me that it looks like I wasn't in the right folder which set me straight.

**Comment by duncanlutz** [comment]
Good to hear that updating fixed the issue! This is a very good point, I'll be adding this to the documentation for clarification. Thanks so much!
